# Generated by Django 2.1.5 on 2019-02-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='descrition',
            new_name='description',
        ),
    ]
